# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: MicrosoftCorporation.VisualStudioCode
PackageVersion: 1.96.2
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/VSCodeSetup-x64-1.96.2.exe
  InstallerSha256: DABBEB4BF2CDE12560A7DCFAC12F78CB8CC924FD65D68704248434AC8ED04BD0
ManifestType: installer
ManifestVersion: 1.9.0
